/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.BolsaController;
import javax.swing.JOptionPane;
import modelo.Bolsa;
import vista.modeloTabla.ModeloTablaElemento;
import vista.utilidades.Utilidades;

/**
 *
 * @author DEEPIN
 */
public class FrmBolsa extends javax.swing.JDialog {

    private BolsaController bc;
    private ModeloTablaElemento modelo = new ModeloTablaElemento();
    private Integer fila = -1;

    /**
     * Creates new form FrmBolsa
     */
    public FrmBolsa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarCombo();
        cargarTabla();
    }

    private void cargarCombo() {
//        Utilidades.cargarComboTipo(cbxTipo);
//        Utilidades.cargarComboTipo(cbxTipoE);
        Utilidades.cargarComboTipo(cbxTipoBolsa);
    }

    private void limpiar() {
        txtCaracteristica.setText("");
        bc.setElemento(null);
        cargarTabla();
    }

    private void cargarTabla() {
        if (bc != null && bc.getBolsa().getElemento() != null) {
            modelo.setElementos(bc.getBolsa().getElemento());
            tbltabla.setModel(modelo);
            tbltabla.updateUI();
            jScrollPane1.setVisible(true);
        } else {
            jScrollPane1.setVisible(false);
        }
    }

//    private void crear() {
//       
//        bc = new BolsaController(cbxTipo.getSelectedItem().toString(), Integer.parseInt(cbx_nro.getSelectedItem().toString()));
//        cargarTabla();
//
//
//    }
    public void agregarElemento() {
        //validazion
        if (txtCaracteristica.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (bc != null && bc.getElemento() != null) {

                bc.getElemento().setCaracteristica(txtCaracteristica.getText());
                try {

                    bc.modificarElemento(bc.getElemento(), fila);
                    JOptionPane.showMessageDialog(null, "Se ha modificado", "Guardado", JOptionPane.INFORMATION_MESSAGE);
                    limpiar();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(null, "Porfavor genere una bolsa", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBolsa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCaracteristica = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        lblTipoE = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbxNumeroBolsa = new javax.swing.JComboBox<>();
        btnCrearBolsas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbxSeleccionarBolsa = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxTipoBolsa = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxNumeroElementos = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmenuGuardar = new javax.swing.JMenuItem();
        jmenuCargar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmenuGuardarJson = new javax.swing.JMenuItem();
        jmenuCargarJson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos de bolsa");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de bolsa"));
        jPanel2.setLayout(null);

        lblBolsa.setText("BOLSA SIN DATOS ");
        jPanel2.add(lblBolsa);
        lblBolsa.setBounds(20, 50, 640, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 170, 680, 120);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "TABLA"));
        jPanel3.setLayout(null);

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltabla);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 660, 180);

        jLabel3.setText("Caracteristicas:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(200, 30, 100, 17);

        txtCaracteristica.setColumns(20);
        txtCaracteristica.setRows(5);
        jScrollPane2.setViewportView(txtCaracteristica);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(310, 20, 220, 90);

        btnAgregar.setText("Actualizar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar);
        btnAgregar.setBounds(550, 20, 100, 23);

        lblTipoE.setText("TIPO: NO DEFINIDO");
        jPanel3.add(lblTipoE);
        lblTipoE.setBounds(20, 30, 120, 17);

        jButton1.setText("SELECCIONAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(40, 70, 120, 23);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 300, 680, 310);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bolsas"));
        jPanel4.setLayout(null);

        jLabel5.setText("Numero de bolsa:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 40, 110, 17);

        cbxNumeroBolsa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        jPanel4.add(cbxNumeroBolsa);
        cbxNumeroBolsa.setBounds(140, 40, 70, 23);

        btnCrearBolsas.setText("CREAR");
        btnCrearBolsas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearBolsasActionPerformed(evt);
            }
        });
        jPanel4.add(btnCrearBolsas);
        btnCrearBolsas.setBounds(240, 40, 72, 23);

        jLabel7.setText("Selecionar Bolsas:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 100, 110, 17);

        cbxSeleccionarBolsa.setToolTipText("");
        cbxSeleccionarBolsa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSeleccionarBolsaItemStateChanged(evt);
            }
        });
        cbxSeleccionarBolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeleccionarBolsaActionPerformed(evt);
            }
        });
        jPanel4.add(cbxSeleccionarBolsa);
        cbxSeleccionarBolsa.setBounds(150, 100, 160, 23);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jLabel1.setText("Tipo:");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(20, 20, 40, 17);

        cbxTipoBolsa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel5.add(cbxTipoBolsa);
        cbxTipoBolsa.setBounds(90, 20, 110, 23);

        jButton3.setText("MODIFICAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(220, 70, 100, 23);

        jLabel8.setText("Nro E: ");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 60, 40, 17);

        cbxNumeroElementos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel5.add(cbxNumeroElementos);
        cbxNumeroElementos.setBounds(90, 60, 110, 23);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(330, 20, 330, 110);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 10, 680, 150);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(600, 620, 77, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 700, 660);

        jMenu3.setText("File");

        jmenuGuardar.setText("Guardar");
        jmenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuGuardarActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuGuardar);

        jmenuCargar.setText("Cargar");
        jmenuCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCargarActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuCargar);
        jMenu3.add(jSeparator1);

        jmenuGuardarJson.setText("Guardar Json");
        jmenuGuardarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuGuardarJsonActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuGuardarJson);

        jmenuCargarJson.setText("Cargar Json");
        jmenuCargarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCargarJsonActionPerformed(evt);
            }
        });
        jMenu3.add(jmenuCargarJson);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        getAccessibleContext().setAccessibleName("Datos de Bolsa");

        setSize(new java.awt.Dimension(731, 746));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregarElemento();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCrearBolsasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBolsasActionPerformed
        // TODO add your handling code here:
        crearArregloBolsa();
    }//GEN-LAST:event_btnCrearBolsasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (!bc.getBolsa().getNombre().equalsIgnoreCase(BolsaController.NCOMUN)) {
            Integer i = JOptionPane.showConfirmDialog(this, "Esta seguro de cambiar los datos de esta bolsa");
            if (i == JOptionPane.OK_OPTION) {
                cambiarTipoBolsa();
            }
        } else {
            cambiarTipoBolsa();
        }

        Integer posCombo = cbxSeleccionarBolsa.getSelectedIndex();
        Utilidades.cargarComboBolsa(cbxSeleccionarBolsa, bc);
        cbxSeleccionarBolsa.setSelectedIndex(posCombo);
        cbxTipoBolsa.setSelectedIndex(0);
        cbxNumeroBolsa.setSelectedIndex(0);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbxSeleccionarBolsaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSeleccionarBolsaItemStateChanged
        // TODO add your handling code here:
//        cargarDatosBolsaCombo();

    }//GEN-LAST:event_cbxSeleccionarBolsaItemStateChanged

    private void cbxSeleccionarBolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeleccionarBolsaActionPerformed
        // TODO add your handling code here:
        cargarDatosBolsaCombo();
    }//GEN-LAST:event_cbxSeleccionarBolsaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        fila = tbltabla.getSelectedRow();
        lblTipoE.setText("TIPO: NO DEFINIDO");
        if (fila >= 0) {
            bc.setElemento(modelo.getElementos()[fila]);
            lblTipoE.setText("TIPO: " + bc.getElemento().getTipo().toString());
            txtCaracteristica.setText(bc.getElemento().getCaracteristica());
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un dato de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jmenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuGuardarActionPerformed
        // TODO add your handling code here:
        if (bc != null) {
            if (Utilidades.guardarArchivo(bc.getBolsas())) {
                JOptionPane.showMessageDialog(null, "Se ha guardado correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Genere una bolsa", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jmenuGuardarActionPerformed

    private void jmenuCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCargarActionPerformed
        // TODO add your handling code here:

        bc = new BolsaController(1);
        bc.setBolsas(Utilidades.cargarArchivo());
        if (bc.getBolsas() != null) {
            Utilidades.cargarComboBolsa(cbxSeleccionarBolsa, bc);
            btnCrearBolsas.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo cargar", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jmenuCargarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Integer sel = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea salir?");
        if(JOptionPane.OK_OPTION == sel){
            
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jmenuGuardarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuGuardarJsonActionPerformed
        // TODO add your handling code here:
        if (bc != null) {
            if (Utilidades.guardarJson(bc.getBolsas())) {
                JOptionPane.showMessageDialog(null, "Se ha guardado correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar el archivo", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Genere una bolsa", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jmenuGuardarJsonActionPerformed

    private void jmenuCargarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCargarJsonActionPerformed
        // TODO add your handling code here:
        bc = new BolsaController(1);
        bc.setBolsas(Utilidades.cargarJson());
        if (bc.getBolsas() != null) {
            Utilidades.cargarComboBolsa(cbxSeleccionarBolsa, bc);
            btnCrearBolsas.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo cargar", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jmenuCargarJsonActionPerformed

    private void crearArregloBolsa() {
        bc = new BolsaController(Integer.parseInt(cbxNumeroBolsa.getSelectedItem().toString()));
        Utilidades.cargarComboBolsa(cbxSeleccionarBolsa, bc);
        btnCrearBolsas.setEnabled(false);
    }

    public void cargarDatosBolsaCombo() {
        lblBolsa.setText("BOLSA: ");
        try {
            bc.setBolsa(Utilidades.getBolsaCombo(cbxSeleccionarBolsa));
            if (bc.getBolsa().getElemento() != null) {
                lblBolsa.setText("BOLSA: " + bc.getBolsa().getNombre() + " Elementos " + bc.getBolsa().getElemento().length);

            } else {
                lblBolsa.setText("BOLSA: " + bc.getBolsa().getNombre() + " Sin Elementos ");
                JOptionPane.showMessageDialog(null, "Porfavor actualice los datos de esta bolsa", "Error", JOptionPane.ERROR_MESSAGE);

            }
            cargarTabla();
        } catch (Exception e) {
            System.out.println("No se ha cargado primero");
        }
    }

    private void cambiarTipoBolsa() {

        bc.getBolsa().setNombre(Utilidades.getTipoCombo(cbxTipoBolsa).toString());
        bc.getBolsa().setTipo(bc.getBolsa().getNombre());
        bc.crearArregloElemento(Integer.parseInt(cbxNumeroElementos.getSelectedItem().toString()), Utilidades.getTipoCombo(cbxTipoBolsa));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBolsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmBolsa dialog = new FrmBolsa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCrearBolsas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxNumeroBolsa;
    private javax.swing.JComboBox<String> cbxNumeroElementos;
    private javax.swing.JComboBox<String> cbxSeleccionarBolsa;
    private javax.swing.JComboBox<String> cbxTipoBolsa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmenuCargar;
    private javax.swing.JMenuItem jmenuCargarJson;
    private javax.swing.JMenuItem jmenuGuardar;
    private javax.swing.JMenuItem jmenuGuardarJson;
    private javax.swing.JLabel lblBolsa;
    private javax.swing.JLabel lblTipoE;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextArea txtCaracteristica;
    // End of variables declaration//GEN-END:variables
}
